#!/usr/bin/env bash

sudo rm /etc/nginx/sites-enabled/default
sudo cp ./deploy/engine /etc/nginx/sites-available
sudo ln -s /etc/nginx/sites-available/engine /etc/nginx/sites-enabled/engine
sudo service nginx restart
sudo echo "configured nginx"